pip3 install -U Pillow
pip3 install -U PyGithub
pip3 install -U PyPDF2
pip3 install -U PyDictionary
pip3 install -U pygments
pip3 install -U pymediainfo
pip3 install -U pytz
pip3 install -U aiofiles
pip3 install -U asyncurban
pip3 install -U aiohttp
pip3 install -U aria2p
pip3 install -U async_generator
pip3 install -U beautifulsoup4
pip3 install -U bs4
pip3 install -U bwb
pip3 install -U cfscrape
pip3 install -U chromedriver_autoinstaller
pip3 install -U cowpy
pip3 install -U cryptg
pip3 install -U colorama
pip3 install -U cloudscraper
pip3 install -U DateTime
pip3 install -U dnspython
pip3 install emoji==1.7
pip3 install -U faker
pip3 install -U fontTools
pip3 install -U glitch_this
pip3 install -U gTTS-token
pip3 install -U gTTS
pip3 install -U gitpython
pip3 install -U google-api-python-client
pip3 install -U google-auth-oauthlib
pip3 install -U google_images_download
pip3 install -U googletrans
pip3 install -U geopy
pip3 install -U gsearch
pip3 install -U hachoir
pip3 install -U heroku3
pip3 install -U httplib2
pip3 install -U humanize
pip3 install -U justwatch
pip3 install -U lxml
pip3 install -U lottie
pip3 install -U nekos.py
pip3 install -U oauth2client
pip3 install -U openai
pip3 install -U patool
pip3 install -U psycopg2
pip3 install -U psycopg2-binary
pip3 install -U PyLyrics
pip3 install -U pyaztro
pip3 install -U pySmartDL
pip3 install -U pybase64
pip3 install -U pyfiglet
pip3 install -U pylast
pip3 install -U pymongo
pip3 install -U python-barcode
pip3 install -U python-dotenv
pip3 install -U python-magic
pip3 install -U pytube
pip3 install -U pytz
pip3 install -U qrcode
pip3 install -U wand
pip3 install -U regex
pip3 install -U requests
pip3 install -U search-engine-parser
pip3 install -U spamwatch
pip3 install -U selenium
pip3 install -U speedtest-cli
pip3 install -U spotify_token
pip3 install -U spotdl
pip3 install -U sqlalchemy 
pip3 install -U telegraph
pip3 install -U twitter_scraper
pip3 install -U telethon
pip3 install -U html-telegraph-poster
pip3 install -U urbandict
pip3 install -U validators
pip3 install -U wikipedia
pip3 install -U tswift
pip3 install -U youtube-dl
pip3 install -U youtube-search-python
pip3 install -U youtube-search
